title: Python Tutorial Workshop - 2018
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]
minima:
  header_pages:
    - README.md
  show_excerpts: false
  hide_site_feed_link: true

